<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NexaGrid.Core\NexaGrid.Core.csproj" />
    <ProjectReference Include="..\NexaGrid.Shared\NexaGrid.Shared.csproj" />
  </ItemGroup>
</Project>
